name: Generate Quiz Video

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install edge-tts moviepy pillow numpy requests

    - name: Run quizgen script
      run: |
        python quizgen.py

    - name: Move video to Video folder
      run: |
        mkdir -p Video
        mv Videos/*.mp4 Video/

    - name: Commit and push video
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Video/*.mp4
        git commit -m 'Add generated quiz video'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
